# Generated by Django 2.1.7 on 2019-04-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=70)),
                ('costo', models.IntegerField()),
                ('cant_modulos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('beneficiario', models.CharField(max_length=50)),
                ('asesora', models.CharField(max_length=50)),
                ('fecha_matricula', models.DateTimeField()),
                ('fecha_diploma', models.DateField()),
                ('decuento_actual', models.IntegerField()),
                ('descuento_pendiente', models.IntegerField()),
                ('promoción', models.IntegerField()),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='academico.Curso')),
                ('inscrito', models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='academico.Inscrito')),
            ],
        ),
        migrations.CreateModel(
            name='Ugel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=70)),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='ugel',
            field=models.ForeignKey(blank=True, null=True, on_delete='CASCADE', to='academico.Ugel'),
        ),
    ]
