# Generated by Django 2.1.7 on 2019-04-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_auto_20190409_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='observaciones',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
