# Generated by Django 2.1.7 on 2019-04-10 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_matricula_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='observaciones',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
