# Generated by Django 2.1.7 on 2019-04-10 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_inscrito_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='promoción',
        ),
        migrations.AddField(
            model_name='matricula',
            name='promocion',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='observaciones',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='apellidos',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='direccion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='nombres',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='observaciones',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='beneficiario',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='modulos_entregados',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='ugel',
            name='director',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ugel',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
