# Generated by Django 2.1.7 on 2019-04-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_auto_20190410_0258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='curso',
        ),
        migrations.AddField(
            model_name='matricula',
            name='curso',
            field=models.ManyToManyField(null=True, to='academico.Curso'),
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='inscrito',
        ),
        migrations.AddField(
            model_name='matricula',
            name='inscrito',
            field=models.ManyToManyField(null=True, to='academico.Inscrito'),
        ),
    ]
