# Generated by Django 2.1.7 on 2019-04-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_auto_20190410_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='curso',
            field=models.ManyToManyField(to='academico.Curso'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='inscrito',
            field=models.ManyToManyField(to='academico.Inscrito'),
        ),
    ]
